name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests (release)
      run: cargo test --verbose --release
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Format
      run: cargo fmt --all -- --check
